.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. VCcoin_qt test_VCcoin_qt
clean: FORCE
	$(MAKE) -C .. VCcoin_qt_clean test_VCcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_VCcoin_qt_check
VCcoin-qt VCcoin-qt.exe: FORCE
	 $(MAKE) -C .. VCcoin_qt
